# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import document_process_pb2 as proto_dot_document__process__pb2


class DocumentProcessorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessDocument = channel.unary_unary(
                '/document.DocumentProcessorService/ProcessDocument',
                request_serializer=proto_dot_document__process__pb2.ProcessRequest.SerializeToString,
                response_deserializer=proto_dot_document__process__pb2.ProcessResponse.FromString,
                )
        self.CreateEmbedding = channel.unary_unary(
                '/document.DocumentProcessorService/CreateEmbedding',
                request_serializer=proto_dot_document__process__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=proto_dot_document__process__pb2.EmbeddingResponse.FromString,
                )


class DocumentProcessorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentProcessorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessDocument,
                    request_deserializer=proto_dot_document__process__pb2.ProcessRequest.FromString,
                    response_serializer=proto_dot_document__process__pb2.ProcessResponse.SerializeToString,
            ),
            'CreateEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEmbedding,
                    request_deserializer=proto_dot_document__process__pb2.EmbeddingRequest.FromString,
                    response_serializer=proto_dot_document__process__pb2.EmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'document.DocumentProcessorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DocumentProcessorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/document.DocumentProcessorService/ProcessDocument',
            proto_dot_document__process__pb2.ProcessRequest.SerializeToString,
            proto_dot_document__process__pb2.ProcessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/document.DocumentProcessorService/CreateEmbedding',
            proto_dot_document__process__pb2.EmbeddingRequest.SerializeToString,
            proto_dot_document__process__pb2.EmbeddingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
