version: '3.8'

services:
  document-ingestion:
    build: ./document-ingestion
    ports: 
            - "8080:8080"
    environment:
            - PROCESSING_SERVICE_ADDR=document-processing:50052
    env_file:
            - ./document-ingestion/.env
    depends_on:
            - document-processing

  document-processing:
    build: ./document-process
    ports:
        - "8081:8081"
        - "50052:50052"
    env_file:
        - ./document-process/.env 