version: '3.8'

services:
  document-ingestion:
    build: ./document-ingestion
    ports: 
            - "8080:8080"
            - "50051:50051"
    volumes:
            - ./document-ingestion/app:/app/app  # Mount the locally built binary
            - ./document-ingestion/static:/app/static  # Mount static files if needed
    environment:
            - PROCESSING_SERVICE_ADDR=document-processing:50052
